[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
select = [
    "B",
    "E",
    "F",
    "W",
    "UP",
]
ignore = [
    "E501",
]
